### ISSUE TITLE
Cannot see Xen VMs

### ISSUE THREAD

**Issue by alejandrobb93** [zipurman/oVIRT_Simple_Backup#33]
Hi, I'm surely missing something but I can't see the Xen VM list, I specified the Xen host IP and Xen migration VM IP and UUID. I also copied the ssh key and the _xe vm-list_ remote command works perfectly from the command line, and it shows like 15 or 16 VMs. 

Can you please enlighten me a bit about what can be missing in my settings or in my Xen host?

![image](https://user-images.githubusercontent.com/33620747/46616616-36dfeb00-cb1b-11e8-811c-1075ac20648d.png)

**Comment by alejandrobb93** [comment]
I am using XenServer 7.0 btw, not 7.2, maybe it is not compatible?

**Comment by zipurman** [comment]
Xen 7.0 should work. I dont have a Xen environment to test anymore but if you catch me on IRC I should be able to help.

Make sure you have done all of what is listed here:
https://github.com/zipurman/oVIRT_Simple_Backup/blob/master/docs/install_debian.md

In the above instructions, there is a part where you "su www-data", make sure all steps in that area are completed. The UI of the  oVirtSimpleBackup runs as www-data so that is where you need to make sure all remote commands are able to function.

**Comment by alejandrobb93** [comment]
That was it! Thank you very much
