### ISSUE TITLE
Snapshot only backups

### ISSUE THREAD

**Issue by andresin** [zipurman/oVIRT_Simple_Backup#51]
#### Enhancement

It would be great to be able to do also snapshot only backups

I know this in not really a backup, but I would like to be able to:

- Schedule snapshot creation
- Ability to set a retention and automatically delete snapshot's

If it is too complex to include, I wouldn't mind to do recovery directly on oVirt.

**Comment by zipurman** [comment]
It'd be pretty easy to setup something like that with the API that ovirt has. I dont think those features will be added to simpleBackup only because they arent really part of the backup process. Also, snapshots do create overhead if they are left on the VMs as I understand it, so there would be an impact to performance if all of your VMs had a couple snapshot attached.

**Comment by andresin** [comment]
I will let you know if I implement it myself.

Thanks,
